export const ALL_SOURCES = [
  'reuters',
  'ft',
  'bloomberg',
  'eastmoney',
  'cls',
  'stcn',
  'coindesk',
  'cointelegraph',
  'twitter',
  'sina',
  'tonghuashun',
  'xueqiu',
  'wallstreetcn',
  'theblock',
  'decrypt',
  'blockworks',
  'cnbc',
  'marketwatch',
  'seekingalpha',
  'citicsf',
  'reddit',
  'eafutures',
  'ztqh',
  'zlqh',
  'thsfutures',
  'emfutures',
  'nanhua',
  'gtjaqh',
  'htqh',
] as const

export type SourceName = (typeof ALL_SOURCES)[number]
